version: '3.8'

services:
  squid:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    restart: unless-stopped
    environment:
      - TZ=UTC
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - squid_cache:/var/spool/squid
    networks:
      - proxy-network

volumes:
  squid_cache:

networks:
  proxy-network:
    driver: bridge